functionsDirectory = "/Users/shane/tradieautomate/repo/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/shane/tradieautomate/repo/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install && npm run build"
functions = "/Users/shane/tradieautomate/repo/netlify/functions"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/blog/sell-your-solar-business-servicem8/"
to = "/blog/sell-servicem8-trade-business-value/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/sell-your-solar-business-servicem8"
to = "/blog/sell-servicem8-trade-business-value/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/blog/best-job-management-software-electricians-australia"
to = "/blog/best-job-management-software-electricians-australia/"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]